import type {
  BankAccount,
  InstitutionOption,
  TransactionRecord,
} from '@/types/finance';
import {
  defaultKycProfile,
  nigerianBanks,
  seedExternalRecipients,
} from '@/lib/nigeria';

export const USE_MOCK_DATA = true;

export { defaultKycProfile, nigerianBanks as seedInstitutions, seedExternalRecipients as seedRecipients };

const ACCOUNT_HOLDER = defaultKycProfile.legalName;

export const seedBanks: BankAccount[] = [
  {
    id: 'ng_bank_01',
    institutionName: 'Guaranty Trust Bank (GTBank)',
    bankCode: '058',
    shortName: 'GTBank',
    accountName: ACCOUNT_HOLDER,
    accountNumber: '0123456789',
    accountNumberMasked: '0123456789',
    accountType: 'savings',
    lastFour: '6789',
    balance: { current: 850000.5, available: 850000.5, currency: 'NGN' },
    isPrimary: true,
    colorTheme: '#DD4B39',
    connectionStatus: 'active',
  },
  {
    id: 'ng_bank_02',
    institutionName: 'Kuda Microfinance Bank',
    bankCode: '50211',
    shortName: 'Kuda',
    accountName: ACCOUNT_HOLDER,
    accountNumber: '2012345678',
    accountNumberMasked: '2012345678',
    accountType: 'spend_save',
    lastFour: '5678',
    balance: { current: 145000.0, available: 145000.0, currency: 'NGN' },
    isPrimary: false,
    colorTheme: '#40196C',
    connectionStatus: 'active',
  },
  {
    id: 'ng_bank_03',
    institutionName: 'Access Bank',
    bankCode: '044',
    shortName: 'Access',
    accountName: ACCOUNT_HOLDER,
    accountNumber: '0691122334',
    accountNumberMasked: '0691122334',
    accountType: 'current',
    lastFour: '2334',
    balance: { current: 2340500.0, available: 2310800.0, currency: 'NGN' },
    isPrimary: false,
    colorTheme: '#0033A1',
    connectionStatus: 'active',
  },
  {
    id: 'ng_bank_04',
    institutionName: 'OPay Digital Services',
    bankCode: '100004',
    shortName: 'OPay',
    accountName: ACCOUNT_HOLDER,
    accountNumber: '8102233445',
    accountNumberMasked: '8102233445',
    accountType: 'wallet',
    lastFour: '3445',
    balance: { current: 38400.0, available: 38400.0, currency: 'NGN' },
    isPrimary: false,
    colorTheme: '#1DCF9F',
    connectionStatus: 'active',
  },
];

export const seedTransactions: TransactionRecord[] = [
  {
    id: 'tx_ng_101',
    timestamp: '2026-09-18T13:32:00Z',
    merchant: { name: 'MTN Airtime', category: 'Airtime / Data', icon: 'smartphone' },
    amount: -5000,
    currency: 'NGN',
    status: 'completed',
    type: 'debit',
    bankId: 'ng_bank_02',
    bankName: 'Kuda Microfinance Bank',
  },
  {
    id: 'tx_ng_102',
    timestamp: '2026-09-18T08:15:00Z',
    merchant: { name: 'GTBank Salary / Acme NG', category: 'Income', icon: 'arrow-down-left' },
    amount: 850000,
    currency: 'NGN',
    status: 'completed',
    type: 'credit',
    bankId: 'ng_bank_01',
    bankName: 'Guaranty Trust Bank (GTBank)',
  },
  {
    id: 'tx_ng_103',
    timestamp: '2026-09-17T16:40:00Z',
    merchant: { name: 'Shoprite Ikeja City Mall', category: 'Groceries', icon: 'shopping-bag' },
    amount: -47250.4,
    currency: 'NGN',
    status: 'completed',
    type: 'debit',
    bankId: 'ng_bank_03',
    bankName: 'Access Bank',
  },
  {
    id: 'tx_ng_104',
    timestamp: '2026-09-17T10:05:00Z',
    merchant: { name: 'Airtel Data Bundle', category: 'Airtime / Data', icon: 'smartphone' },
    amount: -3500,
    currency: 'NGN',
    status: 'completed',
    type: 'debit',
    bankId: 'ng_bank_04',
    bankName: 'OPay Digital Services',
  },
  {
    id: 'tx_ng_105',
    timestamp: '2026-09-16T19:12:00Z',
    merchant: { name: 'IKEDC Prepaid Token', category: 'Utilities', icon: 'zap' },
    amount: -18500,
    currency: 'NGN',
    status: 'completed',
    type: 'debit',
    bankId: 'ng_bank_01',
    bankName: 'Guaranty Trust Bank (GTBank)',
  },
  {
    id: 'tx_ng_106',
    timestamp: '2026-09-16T09:00:00Z',
    merchant: { name: 'Flutterwave Payout', category: 'Income', icon: 'arrow-down-left' },
    amount: 180000,
    currency: 'NGN',
    status: 'completed',
    type: 'credit',
    bankId: 'ng_bank_03',
    bankName: 'Access Bank',
  },
  {
    id: 'tx_ng_107',
    timestamp: '2026-09-15T14:22:00Z',
    merchant: { name: 'Jumia', category: 'Shopping', icon: 'shopping-bag' },
    amount: -34990,
    currency: 'NGN',
    status: 'completed',
    type: 'debit',
    bankId: 'ng_bank_03',
    bankName: 'Access Bank',
  },
  {
    id: 'tx_ng_108',
    timestamp: '2026-09-15T11:08:00Z',
    merchant: { name: 'NIP to ADAMU BELLO SANI', category: 'Transfers', icon: 'repeat' },
    amount: -25000,
    currency: 'NGN',
    status: 'completed',
    type: 'debit',
    bankId: 'ng_bank_01',
    bankName: 'Guaranty Trust Bank (GTBank)',
  },
  {
    id: 'tx_ng_109',
    timestamp: '2026-09-14T18:44:00Z',
    merchant: { name: 'SPAR Magodo', category: 'Groceries', icon: 'shopping-bag' },
    amount: -12800,
    currency: 'NGN',
    status: 'completed',
    type: 'debit',
    bankId: 'ng_bank_02',
    bankName: 'Kuda Microfinance Bank',
  },
  {
    id: 'tx_ng_110',
    timestamp: '2026-09-14T12:10:00Z',
    merchant: { name: 'DSTV Compact', category: 'Bills', icon: 'monitor' },
    amount: -24500,
    currency: 'NGN',
    status: 'completed',
    type: 'debit',
    bankId: 'ng_bank_01',
    bankName: 'Guaranty Trust Bank (GTBank)',
  },
  {
    id: 'tx_ng_111',
    timestamp: '2026-09-13T08:30:00Z',
    merchant: { name: 'Glo Data', category: 'Airtime / Data', icon: 'smartphone' },
    amount: -2000,
    currency: 'NGN',
    status: 'completed',
    type: 'debit',
    bankId: 'ng_bank_04',
    bankName: 'OPay Digital Services',
  },
  {
    id: 'tx_ng_112',
    timestamp: '2026-09-12T20:15:00Z',
    merchant: { name: 'POS Charge · Shoprite', category: 'Transfers', icon: 'repeat' },
    amount: -50,
    currency: 'NGN',
    status: 'completed',
    type: 'debit',
    bankId: 'ng_bank_03',
    bankName: 'Access Bank',
  },
  {
    id: 'tx_ng_113',
    timestamp: '2026-09-12T07:40:00Z',
    merchant: { name: 'KEDCO Electricity', category: 'Utilities', icon: 'zap' },
    amount: -9200,
    currency: 'NGN',
    status: 'completed',
    type: 'debit',
    bankId: 'ng_bank_01',
    bankName: 'Guaranty Trust Bank (GTBank)',
  },
  {
    id: 'tx_ng_114',
    timestamp: '2026-09-11T15:05:00Z',
    merchant: { name: 'Bolt Ride', category: 'Transport', icon: 'car' },
    amount: -3200,
    currency: 'NGN',
    status: 'completed',
    type: 'debit',
    bankId: 'ng_bank_02',
    bankName: 'Kuda Microfinance Bank',
  },
  {
    id: 'tx_ng_115',
    timestamp: '2026-09-10T09:20:00Z',
    merchant: { name: 'Self-transfer to Kuda', category: 'Transfers', icon: 'repeat' },
    amount: -40000,
    currency: 'NGN',
    status: 'completed',
    type: 'debit',
    bankId: 'ng_bank_01',
    bankName: 'Guaranty Trust Bank (GTBank)',
  },
  {
    id: 'tx_ng_116',
    timestamp: '2026-09-10T09:20:08Z',
    merchant: { name: 'Self-transfer from GTBank', category: 'Transfers', icon: 'repeat' },
    amount: 40000,
    currency: 'NGN',
    status: 'completed',
    type: 'credit',
    bankId: 'ng_bank_02',
    bankName: 'Kuda Microfinance Bank',
  },
  {
    id: 'tx_ng_117',
    timestamp: '2026-09-19T09:12:00Z',
    merchant: { name: '9mobile Data', category: 'Airtime / Data', icon: 'smartphone' },
    amount: -1500,
    currency: 'NGN',
    status: 'pending',
    type: 'debit',
    bankId: 'ng_bank_04',
    bankName: 'OPay Digital Services',
  },
  {
    id: 'tx_ng_118',
    timestamp: '2026-09-08T11:30:00Z',
    merchant: { name: 'Failed NIP · Union Bank', category: 'Transfers', icon: 'repeat' },
    amount: -150000,
    currency: 'NGN',
    status: 'failed',
    type: 'debit',
    bankId: 'ng_bank_03',
    bankName: 'Access Bank',
  },
  {
    id: 'tx_ng_119',
    timestamp: '2026-09-07T13:18:00Z',
    merchant: { name: 'Chicken Republic', category: 'Shopping', icon: 'utensils' },
    amount: -6450,
    currency: 'NGN',
    status: 'completed',
    type: 'debit',
    bankId: 'ng_bank_02',
    bankName: 'Kuda Microfinance Bank',
  },
  {
    id: 'tx_ng_120',
    timestamp: '2026-09-05T06:01:00Z',
    merchant: { name: 'Kuda Interest', category: 'Income', icon: 'coins' },
    amount: 214.3,
    currency: 'NGN',
    status: 'completed',
    type: 'credit',
    bankId: 'ng_bank_02',
    bankName: 'Kuda Microfinance Bank',
  },
  {
    id: 'tx_ng_121',
    timestamp: '2026-08-28T10:00:00Z',
    merchant: { name: 'EKEDC Postpaid', category: 'Utilities', icon: 'zap' },
    amount: -15400,
    currency: 'NGN',
    status: 'completed',
    type: 'debit',
    bankId: 'ng_bank_01',
    bankName: 'Guaranty Trust Bank (GTBank)',
  },
];

export const TRANSACTION_CATEGORIES = [
  'Airtime / Data',
  'Utilities',
  'Groceries',
  'Shopping',
  'Transfers',
  'Income',
  'Bills',
  'Transport',
] as const;

export function institutionByCode(code: string): InstitutionOption | undefined {
  return nigerianBanks.find((bank) => bank.bankCode === code);
}
